// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package portfolio

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Modal1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\"><div class=\"modal-dialog\"><div class=\"modal-content\"><div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\"></div><div class=\"container\"><div class=\"row justify-content-center\"><div class=\"col-lg-8\"><div class=\"modal-body\"><!-- Project details--><h2 class=\"text-uppercase\">Help Desk</h2><p class=\"item-intro text-muted\">CRM system for support operators</p><img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/helpdesk.jpg\" alt=\"...\"><ul class=\"list-inline\"><li><strong>Client:</strong> ICF Caritas Ukraine</li><li><strong>Category:</strong> CRM system, Humanitarian domain</li><li><strong>Backend:</strong> Golang</li><li><strong>Frontend:</strong> React.js</li><li><strong>Database:</strong> PostgreSQL</li><li><strong>Deploy:</strong> DigitalOcean</li></ul><p>The project's goal is to meet the organization's needs for recording, accounting, and monitoring the work of specialists who receive appeals from beneficiaries. Our implementation has replaced Google Spreadsheets, which were used earlier and did not meet the needs of the organization due to the heavy workload (recording up to 1300 appeals per day at peak times. In addition, our development allowed us to significantly strengthen data protection by using the ABAC access control system.</p><button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\"><i class=\"fas fa-xmark me-1\"></i> Close</button></div></div></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
