version: '3'

services:

  complicode:
    build:
      context: .
      dockerfile: complicode.dockerfile
    environment:
      - PORT=80
      - TOKEN=${TOKEN}
      - KEY=${KEY}
    restart: always
    networks:
      - app
    ports:
      - "${PORT}:80"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./data/:/app/data/

networks:
  app:

