// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Clients() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"py-5\"><div class=\"container\"><div class=\"row align-items-center\"><div class=\"col-md-3 col-sm-6 my-3\"><a href=\"https://caritas.ua/\" target=\"_blank\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"assets/img/logos/logocu.png\" alt=\"...\" aria-label=\"ICF Caritas Ukraine\"></a></div><div class=\"col-md-3 col-sm-6 my-3\"><a href=\"https://freelancehunt.com/company/complicode.html\" target=\"_blank\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"assets/img/logos/logofh.png\" alt=\"...\" aria-label=\"Freelancehunt Logo\"></a></div><div class=\"col-md-3 col-sm-6 my-3\"><a href=\"https://upwork.com/agencies/complicode\" target=\"_blank\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"assets/img/logos/upwork.png\" alt=\"...\" aria-label=\"Upwork Logo\"></a></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
